AbsenceSoft.SelfService/Models/Home/CreateAccountViewModel.cs
using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;

namespace AbsenceSoft.SelfService.Models.Home
{
    public class CreateAccountViewModel : IValidatableObject
    {
        public CreateAccountViewModel()
        {
        }

        public CreateAccountViewModel(string verificationKey)
            : this()
        {
            VerificationKey = verificationKey;
        }

        [Required]
        public string VerificationKey { get; set; }

        [Required, DisplayName("Enter Password"), DataType(DataType.Password)]
        public string Password { get; set; }

        [Required, DisplayName("Confirm Password"), DataType(DataType.Password)]
        public string ConfirmNewPassword { get; set; }

        public IEnumerable<ValidationResult> Validate(ValidationContext validationContext)
        {
            List<ValidationResult> results = new List<ValidationResult>();
            if (Password != ConfirmNewPassword)
            {
                results.Add(new ValidationResult("Password and Confirmation do not match"));
            }

            return results;
        }
    }
}

AbsenceSoft.SelfService/Models/Home/ExpiredPasswordViewModel.cs
using AbsenceSoft.Logic.Administration;
using AbsenceSoft.Logic.Security;
using AbsenceSoft.Web;
using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;

namespace AbsenceSoft.SelfService.Models.Home
{
    public class ExpiredPasswordViewModel:IValidatableObject
    {
        [Required, DataType(DataType.EmailAddress)]
        public string Email { get; set; }

        [Required, DisplayName("Current Password"), DataType(DataType.Password)]
        public string CurrentPassword { get; set; }

        [Required, DisplayName("New Password"), DataType(DataType.Password)]
        public string NewPassword { get; set; }

        [Required, DisplayName("Confirm Password"), DataType(DataType.Password)]
        public string ConfirmPassword { get; set; }

        public IEnumerable<ValidationResult> Validate(ValidationContext validationContext)
        {
            List<ValidationResult> results = new List<ValidationResult>();
            if (NewPassword != ConfirmPassword)
            {
                results.Add(new ValidationResult("Password and Confirmation do not match"));
            }

            using (var authService = new AuthenticationService())
            using (var adminService = new AdministrationService())
            {
                var user = adminService.GetUserByEmail(Email);
                if(user != null)
                {
                    if (!adminService.CheckPassword(user, CurrentPassword))
                    {
                        results.Add(new ValidationResult("Current password is not correct", new List<string>() { "CurrentPassword" }));
                    }

                    ICollection<string> errors;
                    if(Current.Customer() != null)
                    {
                        if (!authService.ValidatePasswordAgainstPolicy(Current.Customer().PasswordPolicy, user, NewPassword, out errors))
                        {
                            results.Add(new ValidationResult(string.Join("\n", errors), new List<string>() { "Password" }));
                        }
                    }
                }
            }

            return results;
        }
    }
}

AbsenceSoft.SelfService/Models/Home/ForgotPasswordViewModel.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;

namespace AbsenceSoft.SelfService.Models.Home
{
    public class ForgotPasswordViewModel
    {
        [Required, DataType(DataType.EmailAddress)]
        public string Email { get; set; }
    }
}

AbsenceSoft.SelfService/Areas/Reporting/Controllers/HomeController.cs
using AbsenceSoft.SelfService.Controllers;
using AbsenceSoft.SelfService.Models;
using AbsenceSoft.SelfService.Models.Home;
using AbsenceSoft.SelfService.Models.Reports;
using AbsenceSoft.Web;
using AbsenceSoft.Web.Attributes;
using AT.Common.Core;
using Newtonsoft.Json;
using System;
using System.Collections.Generic;
using System.Threading.Tasks;
using System.Web.Mvc;

namespace AbsenceSoft.SelfService.Areas.Reporting.Controllers
{
    public class HomeController : Controller
    {
        // GET: Reporting/Home
        [Secure("MyEmployeesDashboard")]
        [HttpGet, Title("Reports")]
        public ActionResult Index()
        {
            return View();
        }

        /// <summary>
        /// Gets the toolbar data
        /// </summary>
        /// <returns></returns>
        [ChildActionOnly]
        public ActionResult GetToolbar()
        {
            UserViewModel user = new UserViewModel(Current.User());
            return PartialView("_Toolbar", user);
        }

        /// <summary>
        /// Returns the Logo for Employer
        /// </summary>
        /// <returns></returns>
        [ChildActionOnly]
        public PartialViewResult GetLogo()
        {
            LogoViewModel logo = new LogoViewModel();
            logo.PopulateLogoInformation(Current.Employer(), Current.Customer());
            return PartialView("_Logo", logo);
        }

        /// <summary>
        /// Get the Report List for given Category
        /// </summary>
        /// <param name="categoryName"></param>
        /// <returns></returns>
        private async Task<List<ReportListModel>> GetReportsForCategory(string categoryName)
        {
            ApiExecutionController ctrl = new ApiExecutionController();
            var stringData = await ctrl.CallService(new ApiExecutionController.ExecuteArgs() { Component = "reporting", EndPoint = "reports/ess/type/" + categoryName, Method = "GET", PostedData = "" });
            var jset = new JsonSerializerSettings() { TypeNameHandling = TypeNameHandling.All };
            var results = JsonConvert.DeserializeObject<ResultSet<List<AT.Logic.Reporting.Reports.BaseReport>>>(Convert.ToString(stringData), jset);
            return results;
        }
    }
}

AbsenceSoft.SelfService/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using AbsenceSoft.Web.Attributes;
using AbsenceSoft.Web;
using AbsenceSoft.Logic.Security;
using AbsenceSoft.Common;
using AbsenceSoft.SelfService.Models;
using AbsenceSoft.SelfService.Models.Cases;
using AbsenceSoft.Data.Enums;
using AbsenceSoft.Data.Security;
using AbsenceSoft.Logic.Users;
using AbsenceSoft.Data.Cases;
using AbsenceSoft.Logic.Cases;
using AbsenceSoft.Logic;
using AbsenceSoft.SelfService.Models.Home;
using AbsenceSoft.Data.Customers;
using AbsenceSoft.Logic.Customers;
using AbsenceSoft.Logic.Administration;
using AbsenceSoft.SelfService.Common;
using AT.Logic.Authentication;
using System.Threading.Tasks;
using AT.Entities.Authentication;
using AbsenceSoft.Data.Audit;

namespace AbsenceSoft.SelfService.Controllers
{
    public class HomeController : BaseSelfServiceController
    {
        private ApplicationSignInManager _signInManager;
        public HomeController()
        {

        }
        public HomeController(ApplicationSignInManager applicationSignInManager)
        {
            _signInManager = applicationSignInManager;
        }

        /// <summary>
        /// Gets the new object of ApplicationSignInManager.
        /// </summary>
        /// <value>
        /// The sign in manager.
        /// </value>
        protected ApplicationSignInManager SignInManager
        {
            get
            {
                if (_signInManager == null)
                    _signInManager = new ApplicationSignInManager(HttpContext.GetOwinContext().Authentication);
                return _signInManager;
            }
        }

        [ChildActionOnly, Route("Toolbar", Name = "Toolbar")]
        public PartialViewResult Toolbar()
        {
            UserViewModel user = new UserViewModel(Current.User());
            return PartialView(user);
        }

        [ChildActionOnly, Route("Logo", Name="Logo")]
        public PartialViewResult Logo()
        {
            LogoViewModel logo = new LogoViewModel();
            logo.PopulateLogoInformation(Current.Employer(), Current.Customer());
            return PartialView(logo);
        }

        // GET: Home
        [HttpGet, Route("", Name = "Home")]
        [Secure, Title("Dashboard")]
        public ActionResult Index(int? page, long? status, bool? includeApproved, bool? includePending, bool? includeDenied)
        {
            if (!CurrentUserIsManager)
                return RedirectToRoute(HomeRoute);

            if (!page.HasValue)
                page = 1;

            ListCriteria criteria = new ListCriteria()
            {
                PageSize = 5,
                PageNumber = page.Value
            };

            criteria.Set("Status", status);
            criteria.Set("Approved", includeApproved);
            criteria.Set("Pending", includePending);
            criteria.Set("Denied", includeDenied);
            criteria.Set("ListType", "Team");

            using (var caseService = new CaseService())
            {
                ListResults cases = caseService.CaseList(criteria);
                string[] caseIds = cases.Results.Select(c => c.Get<string>("Id")).ToArray();
                IEnumerable<NoteViewModel> notes = GetCaseNotes(caseIds);                
                IEnumerable <AttachmentViewModel> attachments = GetCaseAttachments(caseIds);
                List<CaseViewModel> theCases = cases.Results.Select(c => new CaseViewModel(
                    c, 
                    true, 
                    notes.Where(n => n.CaseId == c.Get<string>("Id")), 
                    attachments.Where(a => a.CaseId == c.Get<string>("Id"))))
                    .Where(c => c != null).ToList();

                if (theCases == null)
                    theCases = new List<CaseViewModel>();

                if (Request.IsAjaxRequest())
                    return PartialView("CaseList", theCases);

                ViewBag.HasMoreCases = cases.Total > 5;
                return View(theCases);
            }
        }

        private bool CustomerLoginIsDisabledForESS(Customer customer)
        {
            return customer != null && customer.SecuritySettings != null && customer.SecuritySettings.DisableESSLoginPage;
        }

        [Title("Login"), HttpGet]
        [Route("Login", Name = "Login")]
        public async Task<ActionResult> Login()
        {
            if (Request != null && Request.IsAuthenticated)
                await LogoutUser();

            if (CustomerLoginIsDisabledForESS(CurrentCustomer))
                return View("DisabledLoginPage");

            using (var ssoService = new SsoService(CurrentCustomer, CurrentEmployer, CurrentUser))
            {
                LoginViewModel login = new LoginViewModel(ssoService.GetProfile(false));
                return View(login);
            }
        }

        [HttpPost, Title("Login")]
        [Route("Login", Name = "LoginPost")]
        public async Task<ActionResult> Login(LoginViewModel login)
        {
            if (!ModelState.IsValid)
            {
                return View(login);
            }

            Data.Security.User loginUser = null;            

            SignInStatus result = await SignInManager.SignInAsync(login.Email, login.Password,ApplicationType.SelfService);

            using (var service = new AdministrationService())
            {
                loginUser = service.GetUserByEmail(login.Email.ToLowerInvariant());
            }

            if (loginUser != null && CustomerLoginIsDisabledForESS(loginUser.Customer))
            {
                Current.Customer(loginUser.Customer);
                return View("DisabledLoginPage");
            }
            //addtional check
            using (var service = new AuthenticationService())
            {
                if (result == SignInStatus.Ok && !service.ValidEmployeeSelfServiceLogin(loginUser))
                {
                    result = SignInStatus.Error;
                }
            }
            switch (result)
            {
                case SignInStatus.Ok:
                    if (loginUser == null)
                    {
                        AbsenceSoft.Web.AuditLoginHelper.AuditLoginFailure(loginUser, login.Email, LoginType.Failed);
                        ModelState.AddModelError("", "Your login attempt has failed. The username and/or password may be incorrect. If you feel your account is properly registered with us, click on \"Forgot Password\" below to retrieve your account details.");
                        break;
                    }

                    AbsenceSoft.Web.AuditLoginHelper.AuditLogin(loginUser, login.Email);
                    string employeeId = loginUser.EmployeeId;
                    bool isManager = AbsenceSoft.Data.Security.User.Permissions.GetProjectedPermissions(loginUser).Contains(Data.Security.Permission.MyEmployeesDashboard.Id);

                    if (isManager)
                    {
                        return RedirectToRoute("Home");                    
                    }
                    
                    if (!loginUser.Employers.Any(e => e.Roles.Count > 0))
                    {
                        ModelState.AddModelError("", "You do not have permission to access the system and no default role or access has been configured for your account. Please contact your system administrator.");
                        break;
                    }

                    if (Case.AsQueryable().Count(c => c.Employee.Id == employeeId) == 0)
                    {
                        return RedirectToRoute("NewRequest");
                    }

                    return RedirectToRoute("ViewEmployee");
                case SignInStatus.Error:
                    AbsenceSoft.Web.AuditLoginHelper.AuditLoginFailure(loginUser, login.Email, LoginType.Failed);
                    ModelState.AddModelError("", "Your login attempt has failed. The username and/or password may be incorrect. If you feel your account is properly registered with us, click on \"Forgot Password\" below to retrieve your account details.");
                    break;
                case SignInStatus.Locked:
                    AbsenceSoft.Web.AuditLoginHelper.AuditLoginFailure(loginUser, login.Email, LoginType.Locked);
                    ModelState.AddModelError("", "Your account has been locked out for security reasons. You should receive an email with instructions how to unlock your account. Please contact AbsenceSoft team if you still having problem with your login.");
                    break;
                case SignInStatus.Disabled:
                    AbsenceSoft.Web.AuditLoginHelper.AuditLoginFailure(loginUser, login.Email, LoginType.Disabled);
                    ModelState.AddModelError("", "Your account has been locked out for security reasons. You should receive an email with instructions how to unlock your account. Please contact AbsenceSoft team if you still having problem with your login.");
                    break;
                case SignInStatus.Expired:
                    AbsenceSoft.Web.AuditLoginHelper.AuditLoginFailure(loginUser, login.Email, LoginType.Expired);
                    return RedirectToRoute("ExpiredPassword");
            }

            ///If we get this far, something failed and a message should be populated
            return View(login);
            
        }

        [HttpGet, Route("Logout", Name = "Logout")]
        public async Task<ActionResult> Logout()
        {
            AbsenceSoft.Web.AuditLoginHelper.AuditLogout(CurrentUser, CurrentUser.Email);
            if (Request != null && Request.IsAuthenticated)
                await LogoutUser();
            return RedirectToRoute("Login");
        }

        private async Task LogoutUser()
        {
            try
            {
                await SignInManager.SignOutAsync();
            }
            catch (Exception ex)

AbsenceSoft.SelfService/Controllers/SSOController.cs
using AbsenceSoft.Web.Controllers;
using AT.Entities.Authentication;
using System.Threading.Tasks;
using System.Web.Mvc;

namespace AbsenceSoft.SelfService.Controllers
{
    public class SSOController : BaseSSOController
    {
        public SSOController() : base(ApplicationType.SelfService)
        {

        }
        // urn:oasis:names:tc:SAML:2.0:bindings:HTTP-POST
        [HttpPost]
        [Route("SSO/saml2/AssertionConsumerService")]
        public async override Task<System.Web.Mvc.ActionResult> AssertionConsumerService()
        {
            return await base.AssertionConsumerService();
        }

        // urn:oasis:names:tc:SAML:2.0:bindings:HTTP-Artifact
        [HttpPost]
        [Route("SSO/saml2/AssertionConsumerService.artifact")]
        public async override Task<System.Web.Mvc.ActionResult> AssertionConsumerServiceArtifact()
        {
            return await base.AssertionConsumerServiceArtifact();
        }

        // urn:oasis:names:tc:SAML:2.0:bindings:HTTP-Redirect
        [HttpGet]
        [Route("SSO/saml2/AssertionConsumerService.redirect")]
        public async override Task<System.Web.Mvc.ActionResult> AssertionConsumerServiceRedirect()
        {
            return await base.AssertionConsumerServiceRedirect();
        }

        [HttpGet]
        [Route("SSO/saml2/SLOService")]
        public override System.Web.Mvc.ActionResult SloService()
        {
            return base.SloService();
        }
    }
}

AbsenceSoft.SelfService/Views/Home/CreateAccount.cshtml
@model AbsenceSoft.SelfService.Models.Home.CreateAccountViewModel
@{
    Layout = "~/Views/Shared/_LoginAndChangePasswordLayout.cshtml";
}

<div class="forgot-password">
    @using (Html.BeginRouteForm("CreateAccountSubmit", FormMethod.Post))
    {
        @Html.AntiForgeryToken()
        @Html.HiddenFor(m => m.VerificationKey)
        <h4 class="white">COMPLETE ACCOUNT REGISTRATION</h4>

        <div class="form-group login-pass">
            @Html.EditorFor(m => m.Password, new
       {
           htmlAttributes =
                new { placeholder = Html.DisplayNameFor(m => m.Password) }
       })
        </div>
        <br />
        <div class="form-group login-pass">
            @Html.EditorFor(m => m.ConfirmNewPassword, new
       {
           htmlAttributes =
                new { placeholder = Html.DisplayNameFor(m => m.ConfirmNewPassword) }
       })
        </div>
        <div class="row">
            <div class="col-xs-12">
                <input type="submit" value="CREATE ACCOUNT" class="btn btn-ess btn-login" />
            </div>

        </div>
        <div class="term-error">
            @Html.ValidationSummary(true)
        </div>
    }
</div>

AbsenceSoft.SelfService/Views/Home/CreateAccountSubmit.cshtml
@{
    Layout = "~/Views/Shared/_LoginAndChangePasswordLayout.cshtml";
}

<div class="forgot-password">
    <div class="row">
        <div class="col-xs-12">
            <h3 class="white">Your account has been successfully created.</h3>
        </div>
    </div>
    <div class="row">
        <div class="col-xs-12">
            @Html.RouteLink("Click here to login.", "Login", null, new { @class = "btn btn-return-home" })
        </div>
    </div>
</div>

AbsenceSoft.SelfService/Views/Home/DisabledLoginPage.cshtml
@{
    ViewBag.Title = "Login Disabled";
    string loginPageDisabled = "An administrator has disabled logging in via username and password.  Please use the Single Sign On login method.";
    if (CurrentCustomer != null && CurrentCustomer.SecuritySettings != null && !string.IsNullOrWhiteSpace(CurrentCustomer.SecuritySettings.DisabledLoginPageText))
    {
        loginPageDisabled = CurrentCustomer.SecuritySettings.DisabledLoginPageText;
    }
}

<h3 class="white">The Login Page Has Been Disabled</h3>
<p class="white">@Html.Raw(loginPageDisabled)</p>

AbsenceSoft.SelfService/Views/Home/ExpiredPasswordSubmit.cshtml
@{
    Layout = "~/Views/Shared/_LoginAndChangePasswordLayout.cshtml";
}

<div class="forgot-password">
    <div class="row">
        <div class="col-xs-12">
            <h3 class="white">Your password has been successfully changed.</h3>
        </div>
    </div>
    <div class="row">
        <div class="col-xs-12">
            @Html.RouteLink("Return to Login Page", "Login", null, new { @class = "btn btn-return-home" })
        </div>
    </div>
</div>

AbsenceSoft.SelfService/Views/Home/ForgotPassword.cshtml
@model AbsenceSoft.SelfService.Models.Home.ForgotPasswordViewModel
@{
    Layout = "~/Views/Shared/_LoginAndChangePasswordLayout.cshtml";
}
<div class="forgot-password">
    @using (Html.BeginRouteForm("ForgotPasswordSubmit", FormMethod.Post))
    {
        @Html.AntiForgeryToken()
        <h3 class="white">Forgot Password</h3>
        <label>Enter your email address in the field below and click Reset Password to request a password reset for your account.</label>
        <div class="form-group login-email login-email-rounded">
            @Html.EditorFor(m => m.Email, new
   {
       htmlAttributes =
                new { placeholder = @Html.DisplayNameFor(m => m.Email) }
   })
            @Html.ValidationMessageFor(m => m.Email, null, new { @class = "errShow" })
        </div>
        <div class="row">
            <div class="col-xs-12">
                @Html.RouteLink("Cancel", "Login", null, new { @class = "btn btn-cancel-passw" })
                <input type="submit" value="Reset Password" class="btn btn-ess btn-repass" />
            </div>
        </div>
    }
</div>

AbsenceSoft.SelfService/Views/Home/ForgotPasswordSubmit.cshtml
@{
    Layout = "~/Views/Shared/_LoginAndChangePasswordLayout.cshtml";
}

<div class="forgot-password">
    <div class="row">
        <div class="col-xs-12">
            <h3 class="white">An email has been sent with instructions on how to reset your password.</h3>
        </div>
    </div>
    <div class="row">
        <div class="col-xs-12">
            @Html.RouteLink("Return to Login Page", "Login", null, new { @class = "btn btn-return-home" })
        </div>
    </div>
</div>

AbsenceSoft.SelfService/Views/Home/Login.cshtml
@model AbsenceSoft.SelfService.Models.LoginViewModel
@{
    Layout = "~/Views/Shared/_LoginAndChangePasswordLayout.cshtml";
}

@using (Html.BeginRouteForm("Login", FormMethod.Post, new { id = "loginForm" }))
{
    <div class="email-error">
        @Html.ValidationMessageFor(m => m.Email, null, new { @class = "" })
    </div>
    <div class="form-group login-email">
        @Html.EditorFor(m => m.Email, new
   {
       htmlAttributes =
         new { placeholder = @Html.DisplayNameFor(m => m.Email) }
   })
    </div>
    <div class="form-group login-pass">
        @Html.EditorFor(m => m.Password, new
   {
       htmlAttributes =
         new { placeholder = @Html.DisplayNameFor(m => m.Password) }
   })
    </div>
    <div class="pass-error">
        @Html.ValidationMessageFor(m => m.Password)
    </div>
    <div class="form-group">
        <label>
            @Html.EditorFor(m => m.TermsAndConditions)
            By logging into this site, you agree to the site's @Html.ActionLink("Terms and Conditions", "TermsAndConditions", "Home").
        </label>
        <div class="term-error">
            @Html.ValidationMessageFor(m => m.TermsAndConditions, null, new { @class = "" })
        </div>
    </div>
    <input type="submit" value="Login" class="btn btn-ess btn-login" />
    <div class="term-error">
        @Html.ValidationSummary(true)
    </div>
    <div class="form-group">
        @if (CurrentCustomer == null || CurrentCustomer.SecuritySettings == null || CurrentCustomer.SecuritySettings.EnableSelfServiceRegistration)
                {
            <div class="pull-left">@Html.RouteLink("Register New Account", "RegisterAccount")</div>
        }
        <div class="pull-right">@Html.RouteLink("Forgot Password?", "ForgotPassword")</div>
    </div>
}
@if (Model.ShowSsoButton)
{
    <div class="form-group">
        <div class="border-login">
            <span>OR</span>
        </div>
        <div class="defaultlogo @if (Model.ShowLogo) {<text>showlogo</text>} ">
            <a href="@Url.Action("AssertionInitiate", "SSO")" class="btn btn-ess btn-sso">LOGIN WITH @Model.PortalName</a>
        </div>
    </div>
}

<script type="text/javascript">
    window.onload = function () {
        $(".validation-summary-errors").hide();
        if ($(".validation-summary-errors li").text().length > 0) {
            $(".validation-summary-errors li").parent();
            $(".validation-summary-errors").show();
        }
    }
</script>

AbsenceSoft.SelfService/Views/Home/Logo.cshtml
@model AbsenceSoft.SelfService.Models.Home.LogoViewModel

<div class="ess-companylogo pull-right hidden-xs hidden-sm hidden-md">
    @if (!string.IsNullOrEmpty(Model.Url))
    {
        <img src="@Model.Url" title="@Model.Name" />
    }
    else
    {
        <h1>@Model.Name</h1>
    }
</div>

AbsenceSoft.SelfService/Views/Home/RegisterAccount.cshtml
@model AbsenceSoft.SelfService.Models.Home.RegisterAccountSubmitViewModel
@{
    Layout = "~/Views/Shared/_LoginAndChangePasswordLayout.cshtml";
}
<div class="register-account">
    @using (Html.BeginRouteForm("RegisterAccountSubmit", FormMethod.Post))
    {
        @Html.AntiForgeryToken()
        <h4>REGISTER A NEW ACCOUNT</h4>        
        <div class="form-group login-email login-email-rounded">
            @Html.EditorFor(m => m.Email, new
       {
           htmlAttributes =
                new { placeholder = @Html.DisplayNameFor(m => m.Email) }
       })
            @Html.ValidationMessageFor(m => m.Email, null, new { @class = "errShow" })
        </div>
        <label>If the provided email address matches an employee on file, we will send an email to begin the self registration process. Please follow the link provided to create your account and password.</label>
        <div class="row">
            <div class="col-xs-12">
                @Html.RouteLink("Cancel", "Login", null, new { @class = "btn btn-cancel-passw" })
                <input type="submit" value="Register Account" class="btn btn-ess btn-repass" />
            </div>
        </div>
    }
</div>

AbsenceSoft.SelfService/Views/Home/ResetPassword.cshtml
@model AbsenceSoft.SelfService.Models.Home.ResetPasswordViewModel
@{ 
    Layout = "~/Views/Shared/_LoginAndChangePasswordLayout.cshtml";
}

<div class="forgot-password">
    @using (Html.BeginRouteForm("ResetPasswordSubmit", FormMethod.Post))
    {
        @Html.AntiForgeryToken()
        @Html.HiddenFor(m => m.ResetKey)
        <h3 class="white">Reset Password</h3>
        <label>Enter your new password in the fields below and click Reset Password</label>

        <div class="form-group login-pass">
            @Html.EditorFor(m => m.NewPassword, new
       {
           htmlAttributes =
                new { placeholder = Html.DisplayNameFor(m => m.NewPassword) }
       })
        </div>
        <br />
        <div class="form-group login-pass">
            @Html.EditorFor(m => m.ConfirmNewPassword, new
       {
           htmlAttributes =
                new { placeholder = Html.DisplayNameFor(m => m.ConfirmNewPassword) }
       })
        </div>
        <div class="row">
            <div class="col-xs-12">
                @Html.RouteLink("Cancel", "Login", null, new { @class = "btn btn-cancel-passw" })
                <input type="submit" value="Reset Password" class="btn btn-ess btn-repass" />
            </div>

        </div>
        <div class="term-error">
            @Html.ValidationSummary(true)
        </div>
    }
</div>

AbsenceSoft.SelfService/Views/Home/ResetPasswordSubmit.cshtml
@{
    Layout = "~/Views/Shared/_LoginAndChangePasswordLayout.cshtml";
}

<div class="forgot-password">
    <div class="row">
        <div class="col-xs-12">
            <h3 class="white">Your password has been successfully reset.</h3>
        </div>
    </div>
    <div class="row">
        <div class="col-xs-12">
            @Html.RouteLink("Return to Login Page", "Login", null, new { @class = "btn btn-return-home" })
        </div>
    </div>
</div>

AbsenceSoft.SelfService/Views/Home/Unauthorized.cshtml
@{
    Layout = "~/Views/Shared/_UnSecureLayout.cshtml";
}
<style type="text/css">
    #navbar-nav {
        display: none;
    }
</style>
<div class="container body-content">
    <hgroup>
        <h1>Unauthorized.</h1>

        <h2>@T("Errors.Users.Unauthorized", "Sorry, you are not authorized to view that resource. Please consult with your System Administrator.")</h2>

    </hgroup>
</div>